server:
  port: 8081

spring:
  application:
    name: tictactoe-engine
  datasource:
    url: ${ENGINE_DB_URL:jdbc:postgresql://localhost:5433/engine_db}
    username: ${ENGINE_DB_USERNAME:engine}
    password: ${ENGINE_DB_PASSWORD:engine}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

game:
  winning-lines: ${GAME_WINNING_LINES:0,1,2;3,4,5;6,7,8;0,3,6;1,4,7;2,5,8;0,4,8;2,4,6}

management:
  endpoints:
    web:
      exposure:
        include: health,info